apiVersion: v1
kind: Namespace
metadata:
  name: lamp-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: lamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: ashenjay/sms:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: mariadb
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: LKJlkj123@@
        - name: MYSQL_DATABASE
          value: db
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: lamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: ashenjay/phpmyadmin:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: LKJlkj123@@
        - name: MYSQL_DATABASE
          value: db
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: lamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ashenjay/console:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: mariadb
        - name: PMA_USER
          value: root
        - name: PMA_PASSWORD
          value: LKJlkj123@@
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: lamp-app
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: lamp-app
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: lamp-app
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
